#!/bin/bash

# Install Zgen
if [ ! -d "${HOME}/.zgen" ]; then
    echo "Installing Zgen" 
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
elif [ -d "${HOME}/.zgen" ]; then
    echo "Zgen already installed" 
fi


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    brew bundle --file="${HOME}/.Caskfile"
  fi

fi

if [ "$system_type" = "Linux" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing linuxbrew"
    sudo apt install linuxbrew-wrapper
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi
