#!/bin/bash
echo "Kodefant Dotfiles Bootstrap Script" 

# Install Zgen
if [ ! -d "${HOME}/.zgen" ]; then
    echo "Installing Zgen" 
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
elif [ -d "${HOME}/.zgen" ]; then
    echo "Zgen already installed" 
fi

system_type=$(uname -s)


# If system is OS X
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    brew bundle --file="${HOME}/.Caskfile"
  fi

  # After Brewfile install
  if [ ! -f "/usr/local/bin/valet" ]; then 
    ## Install Laravel Valet for Mac
    echo "Installing Laravel Valet"
    composer global require laravel/valet
    valet install
  fi
fi

# If system is Linux
if [ "$system_type" = "Linux" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing linuxbrew"
    sudo apt install linuxbrew-wrapper
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ ! -f /usr/local/bin/valet ]; then
    echo "Installing Laravel Valet for Linux" 
    composer global require cpriego/valet-linux
    valet install
  fi

fi

# Make ZSH default shell
chsh -s /bin/zsh

# PHP Remove
echo "If Composer does not run try changing, try adding: pcre.jit=0 to php.ini"
php --ini

# Install Laravel
if [ ! -f "$HOME/.composer/vendor/bin/laravel" ]; then
  echo "Installing Laravel" 
  composer global require laravel/installer
fi

# Install fzf
if [ ! -f ~/.fzf.zsh ]; then
  $(brew --prefix)/opt/fzf/install
fi

# Decrypt files
read -p "Decrypt personal files (y/n)?" choice
case "$choice" in 
  y|Y ) yadm decrypt ;;
esac

if [ ! -d "${HOME}/kode" ]; then
  mkdir ~/kode
fi

open https://www.lastpass.com/
open https://gitftp-deploy.com/
open https://getcoldturkey.com/
echo "Restart your computer for all changes to take Effect"